
-- create
CREATE TABLE CLASSMATES (
  empId INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATES VALUES (0001, 'Ivan', 18,'Moscow');
INSERT INTO CLASSMATES VALUES (0002, 'Oleg', 22,'Vologda');
INSERT INTO CLASSMATES VALUES (0003, 'Daria', 21,'Kostroma');
INSERT INTO CLASSMATES VALUES (0004, 'Oksana', 30,'Pscov');
INSERT INTO CLASSMATES VALUES (0005, 'Denis', 45,'Moscow');
INSERT INTO CLASSMATES VALUES (0006, 'Vika', 33,'Moscow');
INSERT INTO CLASSMATES VALUES (0007, 'Rose',20,'Moscow');
INSERT INTO CLASSMATES VALUES (0008, 'Lena',30,'Moscow');



-- fetch 
SELECT Name FROM CLASSMATES WHERE address = 'Moscow' AND age >=18 AND age <30 
